name: Build and deploy

on:
  push:
    branches: [ master ]


  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Azure Container Registry Build
        uses: Azure/acr-build@v1
        with:
          service_principal: "${{ secrets.servicePrincipalId }}"
          # Service Principal password
          service_principal_password: "${{ secrets.servicePrincipalPassword }}"
          # Azure Container Registry tenant
          tenant: "${{ secrets.tenantId }}"
          # The name of the ACR, minus the .azurecr.io
          registry: authcontainerappexample
          # Repository to use
          repository: secured-app
          tag: ${{ github.sha }}
          # Docker image name
          image: secured-app
          # The folder in the Github repo that holds the source
          folder: .
          # The location of the Dockerfile; defaults to ./Dockerfile
          dockerfile: src/SecuredApi/Dockerfile
    outputs:
      imageTag: ${{ github.sha }}
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      -   uses: actions/checkout@v2
  
      -   name: Azure Login
          uses: Azure/login@v1.1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      -   name: Deploy infrastructure
          uses: azure/arm-deploy@v1
          with:
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
            resourceGroupName: ${{ secrets.AZURE_RG}}
            template: ./bicep/infra.bicep
            parameters: authClientSecret="${{ secrets.AUTH_CLIENT_SECRET }}" authClientId="${{ secrets.AUTH_CLIENT_ID }}" imageTag=${{ needs.build.outputs.imageTag }}
